name: ShellCheck

on:
  push:
  pull_request:

jobs:
  shellcheck:
    name: shellcheck scripts/*
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: Run ShellCheck
        run: |
          echo "Running shellcheck on scripts/*"
          shellcheck --version
          shellcheck scripts/*

